name: Build Windows 7 EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Получаем файлы
      uses: actions/checkout@v4

    - name: Устанавливаем Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Устанавливаем библиотеки
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install pyinstaller==5.13.2

    - name: Собираем EXE файл (СИЛОВОЙ ЗАХВАТ БИНАРНИКОВ)
      run: python -m PyInstaller --noconsole --onefile --collect-all customtkinter --collect-all cv2 --collect-all numpy --collect-all vtracer app.py

    - name: Сохраняем готовый файл
      uses: actions/upload-artifact@v4
      with:
        name: VectorMaster-Win7-Edition
        path: dist/app.exe
