name: Build Windows 7 EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Получаем файлы
      uses: actions/checkout@v4

    - name: Устанавливаем Python 3.9 (Для Windows 7)
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Устанавливаем библиотеки
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Собираем EXE файл
      run: pyinstaller --noconsole --onefile app.py

    - name: Сохраняем готовый файл
      uses: actions/upload-artifact@v4
      with:
        name: VectorMaster-Win7-Edition
        path: dist/app.exe
