name: Build Windows 7 EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Получаем файлы
      uses: actions/checkout@v4

    - name: Устанавливаем Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Железобетонная сборка (Изоляция + Старый Pip)
      run: |
        python -m venv venv
        .\venv\Scripts\python.exe -m pip install pip==23.3.1
        .\venv\Scripts\pip.exe install -r requirements.txt
        .\venv\Scripts\pip.exe install pyinstaller==5.13.2
        .\venv\Scripts\pyinstaller.exe --noconsole --onefile --collect-all customtkinter --collect-all cv2 --collect-all numpy --collect-all vtracer app.py

    - name: Сохраняем готовый файл
      uses: actions/upload-artifact@v4
      with:
        name: VectorMaster-Win7-Edition
        path: dist/app.exe

